name: postgresql_github-action-testing_database1

on: 
  push: 
    branches: [main]
  pull:
    branches: [main]
  workflow_dispatch:
jobs:
build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
    - uses: Azure/login@v1
    with:
      creds: ${ secrets.AZURE_CREDENTIALS }
- uses: azure/postgresql@v1
  with:
    server-name: database1
    connection-string: ${ secrets.AZURE_POSTGRESQLFLEXIBLE_CONNECTION_STRING }
    plsql-file: "sqlpath.sql"
- name: logout
  run: |
    az logout